spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5433/user_service
    username: ${DB_USERNAME:manhdat}
    password: ${DB_PASSWORD:123}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

server:
  port: 8081
jwt:
  secret: VGhpc0lzQVNlY3VyZUp3dFNlY3JldEtleUZvclRUVE4yMDI2MTIzNDU2Nzg5MDEyMzQ1
  expiration: 3600000