#!/usr/bin/env python3
"""Generates infra/seed/products.json (~60 products) for product-service's seed runner.

Stdlib only, deterministic (`random.seed(42)`): running it twice writes byte-identical output.

- brands/categories and the 10 ORIGINAL products are read from the current products.json
  and kept verbatim (sku/name/slug/description/prices/face_shapes/first variant/images);
  they only gain `material_type`, frame measurements, 1-3 extra variants and an image `kind`.
- ~50 extra products are generated over the 8 brands x 8 frame shapes. They are
  ILLUSTRATIVE data for the thesis: model names are made up and images reuse the files of
  an original product with the same frame shape (OVAL/WAYFARER have none, so they borrow
  the closest-looking frames).
- Every product gets exactly one product-level `kind: "TRY_ON"` image: a transparent PNG
  from web/public/products/frames/ (checked to have an alpha channel).

Usage: python3 infra/scripts/generate-seed-products.py
"""
import ast
import json
import random
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SEED_FILE = REPO_ROOT / "infra" / "seed" / "products.json"
FRAMES_DIR = REPO_ROOT / "web" / "public" / "products" / "frames"
FACE_SHAPE_MAPPING_FILE = REPO_ROOT / "recommendation-service" / "app" / "core" / "face_shape_mapping.py"

SEED_COMMENT = (
    "Seed data for product-service (product_db). GENERATED by infra/scripts/generate-seed-products.py "
    "— edit the script, not this file. One product = one object with nested variants[] and images[]; "
    "brand/category are referenced by name so the seed runner can look up/create the parent rows. "
    "frame_shape is the FRAME shape (enum: ROUND|SQUARE|OVAL|CAT_EYE|AVIATOR|RECTANGLE|WAYFARER|RIMLESS); "
    "face_shapes lists the FACE shapes the product suits. material_type is one of "
    "ACETATE|METAL|TITANIUM|TR90|PLASTIC|MIXED (material stays the free-text Vietnamese label); "
    "lens/bridge/temple/frame width are integers in mm. Image kind is GALLERY or TRY_ON (exactly one "
    "product-level TRY_ON transparent PNG per product). base_price/extra_price are in VND (no decimals "
    "in practice, stored as numeric(10,2)). Products after the first 10 are illustrative data for the thesis."
)

ORIGINAL_SKUS = (
    "EB-RIML-025", "VG-AVI-026", "VG-CATEYE-027", "CA-AVI-028", "WP-RND-029",
    "PS-CATEYE-030", "GC-SQR-031", "PR-SQR-032", "OP-RECT-033", "PS-AVI-034",
)

FRAME_SHAPES = ("ROUND", "OVAL", "CAT_EYE", "AVIATOR", "RECTANGLE", "SQUARE", "WAYFARER", "RIMLESS")

# Products generated per frame shape; with the 10 originals every shape ends at 7-8 products (60 total).
NEW_PRODUCTS_PER_SHAPE = {
    "ROUND": 6, "OVAL": 7, "CAT_EYE": 6, "AVIATOR": 5,
    "RECTANGLE": 6, "SQUARE": 6, "WAYFARER": 8, "RIMLESS": 6,
}

SHAPE_CODE = {
    "ROUND": "RND", "OVAL": "OVL", "CAT_EYE": "CATEYE", "AVIATOR": "AVI",
    "RECTANGLE": "RECT", "SQUARE": "SQR", "WAYFARER": "WAY", "RIMLESS": "RIML",
}
SHAPE_LABEL_EN = {
    "ROUND": "Round", "OVAL": "Oval", "CAT_EYE": "Cat-Eye", "AVIATOR": "Aviator",
    "RECTANGLE": "Rectangle", "SQUARE": "Square", "WAYFARER": "Wayfarer", "RIMLESS": "Rimless",
}
SHAPE_LABEL_VI = {
    "ROUND": "dáng tròn", "OVAL": "dáng oval", "CAT_EYE": "dáng mắt mèo", "AVIATOR": "dáng phi công",
    "RECTANGLE": "dáng chữ nhật", "SQUARE": "dáng vuông", "WAYFARER": "dáng wayfarer", "RIMLESS": "không viền",
}
SHAPE_STYLES_VI = {
    "ROUND": ["mang hơi hướng cổ điển, tri thức", "mềm mại, giúp gương mặt góc cạnh trông dịu hơn"],
    "OVAL": ["cân đối, nhẹ nhàng, dễ đeo hằng ngày", "thanh lịch, phù hợp môi trường công sở"],
    "CAT_EYE": ["nữ tính, tôn nét cá tính", "khoé gọng xếch nhẹ, trẻ trung và thời thượng"],
    "AVIATOR": ["cầu mũi kép, phong cách mạnh mẽ, phóng khoáng", "cổ điển, lịch lãm, hợp cả đi làm lẫn dạo phố"],
    "RECTANGLE": ["đường nét gọn gàng, chuyên nghiệp", "tối giản, phù hợp môi trường công sở"],
    "SQUARE": ["bản gọng dày, cá tính và hiện đại", "góc cạnh rõ ràng, tạo điểm nhấn cho gương mặt"],
    "WAYFARER": ["kinh điển, trẻ trung, dễ phối đồ", "phần mày gọng đậm, phong cách năng động"],
    "RIMLESS": ["siêu nhẹ, gần như không cảm giác khi đeo", "tối giản, tinh tế, hợp phong cách lịch lãm"],
}

# Frame shapes without an original product borrow the closest-looking original frames.
IMAGE_SOURCE_FALLBACK = {
    "OVAL": ("OP-RECT-033", "WP-RND-029"),
    "WAYFARER": ("PR-SQR-032",),
}

MATERIAL_LABEL_VI = {
    "ACETATE": "Nhựa Acetate", "METAL": "Kim loại", "TITANIUM": "Titan",
    "TR90": "Nhựa dẻo TR90", "PLASTIC": "Nhựa", "MIXED": "Kết hợp kim loại & nhựa",
}
MATERIAL_PHRASE_VI = {
    "ACETATE": "nhựa Acetate", "METAL": "kim loại", "TITANIUM": "titan",
    "TR90": "nhựa dẻo TR90", "PLASTIC": "nhựa", "MIXED": "kết hợp kim loại và nhựa",
}
MATERIAL_BENEFIT_VI = {
    "ACETATE": "chất liệu Acetate bền màu, bóng đẹp",
    "METAL": "khung kim loại mảnh mai nhưng chắc chắn",
    "TITANIUM": "titan siêu nhẹ, chống gỉ, không gây kích ứng da",
    "TR90": "nhựa TR90 dẻo dai, chịu va đập tốt",
    "PLASTIC": "nhựa nhẹ, giá dễ tiếp cận",
    "MIXED": "kết hợp độ chắc của kim loại và vẻ ấm áp của nhựa",
}
# Rotated per frame shape so the 6 material types are spread without odd combos
# (e.g. no acetate rimless frames).
SHAPE_MATERIALS = {
    "RIMLESS": ("TITANIUM", "METAL", "MIXED"),
    "AVIATOR": ("METAL", "TITANIUM", "MIXED"),
    "ROUND": ("ACETATE", "METAL", "TR90", "TITANIUM", "PLASTIC", "MIXED"),
}
DEFAULT_MATERIALS = ("ACETATE", "TR90", "PLASTIC", "MIXED", "ACETATE", "METAL")
LEGACY_MATERIAL_TYPE = {"Nhựa Acetate": "ACETATE", "Kim loại": "METAL"}

# (name, hex, sku code)
PALETTE = {
    "BLK": ("Đen", "#1A1A1A"),
    "SLV": ("Bạc", "#B8B8B8"),
    "GLD": ("Vàng", "#C9A646"),
    "RGD": ("Vàng hồng", "#B76E79"),
    "GRY": ("Xám khói", "#6B6B6B"),
    "TRT": ("Đồi mồi", "#7B4A2A"),
    "CLR": ("Trong suốt", "#E8E8E8"),
    "NVY": ("Xanh navy", "#1F3A5F"),
    "WIN": ("Đỏ rượu vang", "#7B1E2B"),
    "NUD": ("Hồng nude", "#E8B4A8"),
}
METAL_COLOR_CODES = ("SLV", "GLD", "RGD", "BLK", "GRY")
PLASTIC_COLOR_CODES = ("BLK", "TRT", "CLR", "NVY", "WIN", "NUD", "GRY")
MATERIAL_COLOR_CODES = {
    "METAL": METAL_COLOR_CODES, "TITANIUM": METAL_COLOR_CODES,
    "ACETATE": PLASTIC_COLOR_CODES, "TR90": PLASTIC_COLOR_CODES, "PLASTIC": PLASTIC_COLOR_CODES,
    "MIXED": METAL_COLOR_CODES + ("TRT", "NVY", "WIN"),
}

SIZES = ("S", "M", "L")
SIZE_STEP_PRICE = 100000

# Measurements (mm) for size M; S/L shift the lens/bridge.
BASE_LENS_WIDTH = {
    "ROUND": 49, "OVAL": 52, "CAT_EYE": 53, "AVIATOR": 57,
    "RECTANGLE": 54, "SQUARE": 51, "WAYFARER": 52, "RIMLESS": 52,
}
BASE_BRIDGE_WIDTH = {
    "ROUND": 20, "OVAL": 18, "CAT_EYE": 17, "AVIATOR": 15,
    "RECTANGLE": 17, "SQUARE": 18, "WAYFARER": 19, "RIMLESS": 18,
}
SIZE_LENS_OFFSET = {"S": -2, "M": 0, "L": 2}
SIZE_BRIDGE_OFFSET = {"S": -1, "M": 0, "L": 1}
SIZE_TEMPLES = {"S": (135, 140), "M": (140, 145), "L": (145, 150)}
RANGES = {
    "lens_width_mm": (40, 65), "bridge_width_mm": (12, 26),
    "temple_length_mm": (120, 160), "frame_width_mm": (110, 160),
}

# Price bands (VND, step 10k) and the bands each brand plausibly sells in.
PRICE_BANDS = {
    "<1M": (390000, 990000), "1-2M": (1050000, 1990000),
    "2-4M": (2100000, 3900000), ">4M": (4200000, 6500000),
}
BRAND_PRICE_BANDS = {
    "EyeBuyDirect": ("<1M",),
    "Vogue Eyewear": ("<1M", "1-2M"),
    "Warby Parker": ("<1M", "1-2M"),
    "Carrera": ("1-2M",),
    "Persol": ("2-4M",),
    "Oliver Peoples": ("2-4M", ">4M"),
    "Prada": ("2-4M", ">4M"),
    "Gucci": (">4M",),
}
BRAND_SKU_PREFIX = {
    "Carrera": "CA", "Warby Parker": "WP", "Persol": "PS", "Gucci": "GC",
    "Prada": "PR", "Oliver Peoples": "OP", "Vogue Eyewear": "VG", "EyeBuyDirect": "EB",
}
# Made-up model names: a code for brands that number their models, a word otherwise.
BRAND_MODEL_CODE = {
    "Carrera": "CA", "Persol": "PO", "Gucci": "GG", "Prada": "PR", "Oliver Peoples": "OV", "Vogue Eyewear": "VO",
}
MODEL_WORDS = (
    "Linden", "Harlow", "Mercer", "Ashby", "Colton", "Briar", "Soren", "Wren",
    "Tate", "Ellis", "Nolan", "Maren", "Otis", "Rhea", "Sage", "Dalton",
)

# Round-robin gender pattern: 4 UNISEX / 3 FEMALE / 3 MALE per 10 products.
GENDER_PATTERN = ("UNISEX", "FEMALE", "MALE", "UNISEX", "FEMALE", "MALE", "UNISEX", "UNISEX", "FEMALE", "MALE")
GENDER_BASE_SIZES = {"FEMALE": ("S", "M"), "MALE": ("M", "L"), "UNISEX": ("S", "M", "L")}

FIRST_NEW_SKU_NUMBER = 35
CATEGORY = "Gọng kính"


def load_face_fit(min_score: float = 7.0) -> dict[str, list[str]]:
    """frame shape -> face shapes scoring >= min_score, read from recommendation-service's FaceFit matrix."""
    tree = ast.parse(FACE_SHAPE_MAPPING_FILE.read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.AnnAssign) and getattr(node.target, "id", None) == "FACE_SHAPE_TO_FRAME_SHAPES":
            table = node.value
            break
    else:
        raise RuntimeError(f"FACE_SHAPE_TO_FRAME_SHAPES not found in {FACE_SHAPE_MAPPING_FILE}")

    faces_by_frame: dict[str, list[str]] = {shape: [] for shape in FRAME_SHAPES}
    for face_key, pairs in zip(table.keys, table.values):
        face = face_key.attr
        for pair in pairs.elts:
            frame, score = pair.elts[0].attr, pair.elts[1].value
            if score >= min_score:
                faces_by_frame[frame].append(face)
    return faces_by_frame


def assert_transparent_png(image_url: str) -> None:
    path = FRAMES_DIR / Path(image_url).name
    header = path.read_bytes()[:26]
    # PNG signature, then IHDR: colour type byte at offset 25 (4 = grey+alpha, 6 = RGBA).
    if header[:8] != b"\x89PNG\r\n\x1a\n" or header[25] not in (4, 6):
        raise RuntimeError(f"TRY_ON image {path} is not a PNG with an alpha channel")


def image(image_url: str, is_thumbnail: bool, sort_order: int, kind: str, variant_sku: str | None = None) -> dict:
    result = {"image_url": image_url, "is_thumbnail": is_thumbnail, "sort_order": sort_order, "kind": kind}
    if variant_sku:
        result["variant_sku"] = variant_sku
    return result


def image_family(original: dict) -> dict:
    """Split an original product's images into the try-on PNG, gallery photos and the variant photo."""
    product_images = [img for img in original["images"] if not img.get("variant_sku")]
    pngs = [img["image_url"] for img in product_images if img["image_url"].endswith(".png")]
    if len(pngs) != 1:
        raise RuntimeError(f"{original['sku']}: expected exactly one product-level PNG, got {pngs}")
    return {
        "png": pngs[0],
        "gallery": [img["image_url"] for img in product_images if not img["image_url"].endswith(".png")],
        "variant": [img["image_url"] for img in original["images"] if img.get("variant_sku")],
    }


def measurements(rng: random.Random, frame_shape: str, size: str) -> dict:
    lens = BASE_LENS_WIDTH[frame_shape] + SIZE_LENS_OFFSET[size] + rng.randint(-1, 1)
    bridge = BASE_BRIDGE_WIDTH[frame_shape] + SIZE_BRIDGE_OFFSET[size] + rng.randint(-1, 1)
    values = {
        "lens_width_mm": lens,
        "bridge_width_mm": bridge,
        "temple_length_mm": rng.choice(SIZE_TEMPLES[size]),
        "frame_width_mm": 2 * lens + bridge + rng.randint(6, 10),
    }
    for field, (low, high) in RANGES.items():
        if not low <= values[field] <= high:
            raise RuntimeError(f"{field}={values[field]} outside {low}-{high} ({frame_shape} {size})")
    return values


def build_variants(
    rng: random.Random,
    sku: str,
    material_type: str,
    base_size: str,
    first: dict | None = None,
) -> list[dict]:
    """2-4 variants with unique (color, size); `first` (an original product's variant) is kept as-is.

    Sizes above `base_size` cost SIZE_STEP_PRICE more per step; smaller sizes cost the same.
    """
    count = rng.randint(2, 4)
    base_index = SIZES.index(base_size)
    sizes = [base_size]
    if rng.random() < 0.5:
        sizes.append(SIZES[base_index + 1] if base_index + 1 < len(SIZES) else SIZES[base_index - 1])

    colors: list[tuple[str, str, str]] = []  # (code, name, hex)
    if first:
        first_code = first["sku_variant"][len(sku) + 1 : -(len(first["size"]) + 1)]
        colors.append((first_code, first["color"], first["color_hex"]))
    candidate_codes = [code for code in MATERIAL_COLOR_CODES[material_type] if code not in {c[0] for c in colors}]
    rng.shuffle(candidate_codes)
    for code in candidate_codes:
        if first and PALETTE[code][0] == first["color"]:
            continue
        colors.append((code, *PALETTE[code]))

    variants = [first] if first else []
    used = {(first["color"], first["size"])} if first else set()
    for code, name, hex_value in colors:
        for size in sizes:
            if len(variants) == count:
                return variants
            if (name, size) in used:
                continue
            used.add((name, size))
            variants.append({
                "color": name,
                "color_hex": hex_value,
                "size": size,
                "extra_price": SIZE_STEP_PRICE * max(0, SIZES.index(size) - base_index),
                "sku_variant": f"{sku}-{code}-{size}",
                "stock": rng.randint(5, 40),
            })
    return variants


def enrich_original(rng: random.Random, original: dict) -> dict:
    material_type = LEGACY_MATERIAL_TYPE[original["material"]]
    first = original["variants"][0]
    product = {key: original[key] for key in (
        "sku", "name", "slug", "description", "brand", "category",
        "frame_shape", "face_shapes", "gender_target", "material",
    )}
    product["material_type"] = material_type
    product.update(measurements(rng, original["frame_shape"], first["size"]))
    product["base_price"] = original["base_price"]
    product["status"] = original["status"]
    product["variants"] = build_variants(rng, original["sku"], material_type, first["size"], first)

    png = image_family(original)["png"]
    assert_transparent_png(png)
    product["images"] = [
        image(
            img["image_url"], img["is_thumbnail"], img["sort_order"],
            "TRY_ON" if img["image_url"] == png else "GALLERY", img.get("variant_sku"),
        )
        for img in original["images"]
    ]
    return product


def generate_product(
    rng: random.Random,
    number: int,
    frame_shape: str,
    brand: str,
    gender: str,
    material_type: str,
    family: dict,
    face_fit: dict[str, list[str]],
    used_names: set[str],
) -> dict:
    sku = f"{BRAND_SKU_PREFIX[brand]}-{SHAPE_CODE[frame_shape]}-{number:03d}"
    while True:
        if brand in BRAND_MODEL_CODE:
            model = f"{BRAND_MODEL_CODE[brand]}{rng.randint(1000, 9899)}"
        else:
            model = rng.choice(MODEL_WORDS)
        name = f"{brand} {model} {SHAPE_LABEL_EN[frame_shape]}"
        if name not in used_names:
            used_names.add(name)
            break
    slug = "-".join(name.lower().replace("-", " ").split())

    base_size = rng.choice(GENDER_BASE_SIZES[gender])
    variants = build_variants(rng, sku, material_type, base_size)
    low, high = PRICE_BANDS[rng.choice(BRAND_PRICE_BANDS[brand])]
    base_price = rng.randrange(low, high + 1, 10000)

    description = (
        f"Gọng {MATERIAL_PHRASE_VI[material_type]} {SHAPE_LABEL_VI[frame_shape]} "
        f"tông {variants[0]['color'].lower()}, {rng.choice(SHAPE_STYLES_VI[frame_shape])}; "
        f"{MATERIAL_BENEFIT_VI[material_type]}."
    )

    assert_transparent_png(family["png"])
    images = [image(family["png"], True, 0, "TRY_ON")]
    images += [image(url, False, index + 1, "GALLERY") for index, url in enumerate(family["gallery"])]
    images += [image(url, True, 0, "GALLERY", variants[0]["sku_variant"]) for url in family["variant"]]

    product = {
        "sku": sku,
        "name": name,
        "slug": slug,
        "description": description,
        "brand": brand,
        "category": CATEGORY,
        "frame_shape": frame_shape,
        "face_shapes": face_fit[frame_shape],
        "gender_target": gender,
        "material": MATERIAL_LABEL_VI[material_type],
        "material_type": material_type,
    }
    product.update(measurements(rng, frame_shape, base_size))
    product.update({"base_price": base_price, "status": "PUBLISHED", "variants": variants, "images": images})
    return product


def generate(seed_data: dict) -> dict:
    rng = random.Random(42)
    originals_by_sku = {p["sku"]: p for p in seed_data["products"] if p["sku"] in ORIGINAL_SKUS}
    missing = set(ORIGINAL_SKUS) - originals_by_sku.keys()
    if missing:
        raise RuntimeError(f"original products missing from {SEED_FILE}: {sorted(missing)}")
    originals = [originals_by_sku[sku] for sku in ORIGINAL_SKUS]

    products = [enrich_original(rng, original) for original in originals]

    families_by_shape: dict[str, list[dict]] = {shape: [] for shape in FRAME_SHAPES}
    for original in originals:
        families_by_shape[original["frame_shape"]].append(image_family(original))
    for shape, source_skus in IMAGE_SOURCE_FALLBACK.items():
        families_by_shape[shape] = [image_family(originals_by_sku[sku]) for sku in source_skus]

    face_fit = load_face_fit()
    brands = [brand["name"] for brand in seed_data["brands"]]
    used_names = {p["name"] for p in products}
    index = 0
    for frame_shape in FRAME_SHAPES:
        materials = SHAPE_MATERIALS.get(frame_shape, DEFAULT_MATERIALS)
        families = families_by_shape[frame_shape]
        for shape_index in range(NEW_PRODUCTS_PER_SHAPE[frame_shape]):
            gender = GENDER_PATTERN[index % len(GENDER_PATTERN)]
            if frame_shape == "CAT_EYE" and gender == "MALE":
                gender = "FEMALE"
            products.append(generate_product(
                rng,
                FIRST_NEW_SKU_NUMBER + index,
                frame_shape,
                brands[index % len(brands)],
                gender,
                materials[shape_index % len(materials)],
                families[shape_index % len(families)],
                face_fit,
                used_names,
            ))
            index += 1

    return {
        "$comment": SEED_COMMENT,
        "brands": seed_data["brands"],
        "categories": seed_data["categories"],
        "products": products,
    }


def inline(obj: dict) -> str:
    return "{ " + ", ".join(f"{json.dumps(k)}: {json.dumps(v, ensure_ascii=False)}" for k, v in obj.items()) + " }"


def render(seed: dict) -> str:
    """Same layout as the hand-written file: one line per brand/category/variant/image."""
    lines = ["{", f'  "$comment": {json.dumps(seed["$comment"], ensure_ascii=False)},']
    for section in ("brands", "categories"):
        lines.append(f'  "{section}": [')
        rows = [f"    {inline(item)}" for item in seed[section]]
        lines.append(",\n".join(rows))
        lines.append("  ],")
    lines.append('  "products": [')
    product_blocks = []
    for product in seed["products"]:
        fields = []
        for key, value in product.items():
            if key in ("variants", "images"):
                rows = ",\n".join(f"        {inline(item)}" for item in value)
                fields.append(f'      "{key}": [\n{rows}\n      ]')
            elif key == "base_price":
                fields.append(f'      "{key}": {value:.2f}')
            else:
                fields.append(f'      "{key}": {json.dumps(value, ensure_ascii=False)}')
        product_blocks.append("    {\n" + ",\n".join(fields) + "\n    }")
    lines.append(",\n".join(product_blocks))
    lines.append("  ]")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> None:
    seed_data = json.loads(SEED_FILE.read_text(encoding="utf-8"))
    output = render(generate(seed_data))
    json.loads(output)  # fail loudly if the hand-rolled layout is not valid JSON
    SEED_FILE.write_text(output, encoding="utf-8")
    print(f"Wrote {SEED_FILE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
