"""add user_id to face_analyses

Revision ID: 4bc306f02b28
Revises: 932ad020533d
Create Date: 2026-07-16 10:01:00.119578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bc306f02b28'
down_revision: Union[str, Sequence[str], None] = '932ad020533d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face_analyses', sa.Column('user_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('face_analyses', 'user_id')
    # ### end Alembic commands ###
