"""create face_analyses table

Revision ID: 932ad020533d
Revises: 
Create Date: 2026-07-13 08:02:48.469542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '932ad020533d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('face_shape', sa.Enum('ROUND', 'SQUARE', 'OVAL', 'HEART', 'DIAMOND', 'OBLONG', name='face_shape_enum'), nullable=False),
    sa.Column('measurements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('face_analyses')
    # ### end Alembic commands ###
